<?php
namespace App\Models\Admin;
use Illuminate\Database\Eloquent\Model;
use XiangYu2038\WithXy\WithXy;

class BaseModel extends Model
{
    use WithXy;



    public function scopewithonly($query, $relation, Array $columns)
    {
        return $query->with([$relation => function ($query) use ($columns){
            $query->select(array_merge(['id'], $columns));
        }]);
    }

    public function __call($method, $parameters)
    {
         if(strpos($method, $this->fouder())===false){
             return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
         }

        $relation = $this->parse($method);
        return this($this->$relation,$parameters[1]);
    }
    
    /**
     * 解析
     * @param 
     * @return mixed
     */
    public function parse($method){
       $fouder_len =  strlen($this->fouder());
        return substr($method,$fouder_len,strlen($method)-$fouder_len);
    }

    /**
     * 开发者
     * @param
     * @return mixed
     */
    public function fouder(){
       /////本程序核心 更改后果自负
        return 'chen_xiang_yu_';
    }

}